kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: terraform-kubernetes-demo
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30201
    hostPort: 30201
    listenAddress: "0.0.0.0"